### ISSUE TITLE
Database with wrong align when outline enable start from 3.1.0

### ISSUE THREAD

**Issue by finach** [GorvGoyl/Notion-Boost-browser-extension#128] opened 2022-05-22 13:30 UTC
![image](https://user-images.githubusercontent.com/96366890/169697583-047604f6-3e86-4586-8571-e284950ac500.png)

**Comment by GorvGoyl** [comment] 2022-05-22 15:27
I'm not able to reproduce this bug, could you add more details or perhaps a link to the page where this issue is happening

**Comment by finach** [comment] 2022-05-22 16:20
Find the detail steps.
1. disable extension outline
2. disable full width in **notion setting**
3. enable extension outline

Below steps will not happen
1. disable extension outline
2. enable full width in notion setting
3. enable extension outline

So I think the different is that enable/disable full width in notion default setting or not.

Thanks

**Comment by chiyang10000** [comment] 2022-07-08 02:37
@GorvGoyl The Extension released on May 22(quoted from the Chrome shop) seems have not yet included the fix. 👀

**Comment by GorvGoyl** [comment] 2022-08-08 15:23
thanks for reporting. it has been fixed in v.3.1.2

**Closed by GorvGoyl** 2022-08-08 15:23 UTC
Labels: need-more-info
