### ISSUE TITLE
"Small text for all pages" is suddenly making text big!

### ISSUE THREAD

**Issue by vnavone** [GorvGoyl/Notion-Boost-browser-extension#55] opened 2021-09-27 05:15 UTC
I'm using Pro version of 3.0.1 in Chrome and today I noticed that my page links have become giant - about the size of Header 1.  Database contents and regular text blocks are not are not affected.  I have disabled this toggle for now but I'm hoping you can fix this quickly!

**Comment by GorvGoyl** [comment] 2021-09-27 09:42
duplicate of https://github.com/GorvGoyl/Notion-Boost-browser-extension/issues/54

**Closed by GorvGoyl** 2021-09-27 09:42 UTC
