### ISSUE TITLE
Always 'Open As Page' in Databases

### ISSUE THREAD

**Issue by Kireekk** [GorvGoyl/Notion-Boost-browser-extension#24] opened 2021-03-25 19:26 UTC
Always 'Open as Page' in database pages, like lists, tables and other. I'd LOVE to have this feature, it would really make Notion perfect. Please add this. Nice work.

**Comment by GorvGoyl** [comment] 2021-04-28 11:49
Duplicate of #33

**Closed** 2021-09-03 22:19 UTC
