### ISSUE TITLE
Turning on the outline will cause the hyperlinks in the simple table to be quickly offset

### ISSUE THREAD

**Issue by tetsuhou** [GorvGoyl/Notion-Boost-browser-extension#162] opened 2022-11-26 06:05 UTC
I am sorry that my English is not good, so there may be some ambiguity.

The problem is shown in the video. This problem happens when simple table is placed below Heading block.

The browser I use is Firefox, but the same problem can be reproduced on Edge with only Notion Boost installed.

I do not know why the video there is a distance can not display the mouse, but it should not matter.

https://user-images.githubusercontent.com/16057538/204074691-3c9d0dc5-de72-4c1c-9cea-e232e3ec3651.mp4

**Comment by GorvGoyl** [comment] 2023-01-16 07:20
can't reproduce.. please share a public notion page link to test

**Comment by tetsuhou** [comment] 2023-01-16 14:23
Thank you very much for your reply.

I tested the problem without logging in, and found that the problem occurs whenever "outline" appears in the upper right corner of the page and the outline is turned on.

For browsers, if you use edge without login to notion, there is no "outline" in the upper right corner, so you won't have this problem, but if you use firefox without login to notion, there will be an "outline ", then there will be this problem.

https://tetsuhou.notion.site/tetsuhou/test-55c6b6af837447da8a0c95eeff14bfe1

**Comment by GorvGoyl** [comment] 2023-01-16 14:49
fixed in upcoming release

**Comment by tetsuhou** [comment] 2023-01-16 21:35
Thank you very much.

**Closed** 2023-01-17 06:23 UTC
Labels: not-reproducible
