### ISSUE TITLE
Header titles in the outline are not clickable after using  few days

### ISSUE THREAD

**Issue by tyb1m** [GorvGoyl/Notion-Boost-browser-extension#105] opened 2022-02-28 08:38 UTC
Any suggestions? Or just notion updates, which breaks this function?
https://www.awesomescreenshot.com/video/7630672

**Comment by GorvGoyl** [comment] 2022-02-28 09:22
it's been fixed in v3.0.9. please update the extension and restart the browser.

**Comment by GorvGoyl** [comment] 2022-02-28 10:37
can you tell me the version of Notion Boost ext?

**Comment by tyb1m** [comment] 2022-02-28 14:23
Version 3.0.9

2022年2月28日(月) 19:37 Gourav Goyal ***@***.***>:

**Comment by GorvGoyl** [comment] 2022-02-28 14:56
okay, can you share the screenshot/video. I'm not able to access the link you mentioned.

Also, can you open Notion Boost -> about and verify the version to be 3.0.9.

**Comment by tyb1m** [comment] 2022-02-28 15:09
https://ikillc.notion.site/test-8b8212cb70db4ce68a6eb88ea4b5d36b
thank you for your reply and check the link above.

2022年2月28日(月) 23:57 Gourav Goyal ***@***.***>:

**Comment by GorvGoyl** [comment] 2022-03-01 08:35
I'm not able to reproduce this issue from my side. And there are no reports of outline not working by other users. Maybe some other browser extension is conflicting with Notion and Notion Boost? try opening this page in incognito with just Notion Boost extension enabled.


![image](https://user-images.githubusercontent.com/7106086/156133519-bfac91e2-b9a1-46ff-9c77-5d8d8ef098c4.png)

**Comment by tyb1m** [comment] 2022-03-02 08:14
I deleted the extension Queue and solved it.
https://chrome.google.com/webstore/detail/queue/injmafaookciamgplnkakgcloohbbdjg

Sorry for asking you, wrong place to ask...it helped me a lot!
Sort of, in return, I want to buy a pro feature, but it shows error...

"A valid Importer/Exporter Code (IEC) is needed to present in USD. Please
contact contact ***@***.*** if you have any questions."

I will try to solve this, asking them directly..thanks.

2022年3月1日(火) 17:35 Gourav Goyal ***@***.***>:

**Comment by GorvGoyl** [comment] 2022-03-02 10:23
Glad you figured it out.

**Closed by GorvGoyl** 2022-03-02 10:23 UTC
